version: "3"

services:
  api-server:
    container_name: "api-server"
    restart: always
    build: ./api-server/.
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 5001:5001
    volumes:
      - ./api-server:/app
      - /app/node_modules
    networks:
      - mynetwork
  db:
    container_name: "database"
    build: ./db/
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

    ports:
      - "3306:3306"
    command: --init-file /data/application/init_db.sql
    volumes:
      - ./db/init_db.sql:/data/application/init_db.sql
    networks:
      - mynetwork
  client-next:
    build:
      context: ./client-next  # ✅ This tells Docker to use the `client-next/` directory
      dockerfile: Dockerfile  # ✅ Make sure it points to the right Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client-next:/app  # ✅ Mount the correct directory
    command: npm run start
networks:
  mynetwork:
    driver: bridge