version: "3"

services:
  db:
    container_name: "database"
    build: ./db/
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/01_init.sql
    networks:
      - mynetwork

  api-server:
    container_name: "api-server"
    restart: always
    build: ./api-server/.
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    ports:
      - 5001:5001
    networks:
      - mynetwork
  client-next:
    build:
      context: ./client-next  # ✅ This tells Docker to use the `client-next/` directory
      dockerfile: Dockerfile  # ✅ Make sure it points to the right Dockerfile
    ports:
      - "3000:3000"
    command: npm run dev
networks:
  mynetwork:
    driver: bridge