import { Metadata } from 'next';
import './globals.css';

import { WeightUnitProvider } from '@/contexts/weight-unit-context';
import { AuthProvider } from '@/contexts/auth-context';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html>
        <body>
        <AuthProvider>
            <WeightUnitProvider>
                {children}
            </WeightUnitProvider>
        </AuthProvider>
        </body>
        </html>
    );
}
