name: Next.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies on client
        run: npm install
        working-directory: client-next

      - name: Build Project client
        run: npm run build
        working-directory: client-next

      - name: Install Dependencies on server
        run: npm install
        working-directory: api-server

      - name: Create .env file for server
        run: |
          echo "PORT=5001" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_USER=admin" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_DATABASE=traveldb" >> .env
          echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" >> .env
          echo "DATABASE_URL=" >> .env
        working-directory: api-server

      - name: Start API Server
        run: npm run start
        working-directory: api-server
