name: Next.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies on client
        run: npm install
        working-directory: client-next

      - name: Build Project client
        run: npm run build
        working-directory: client-next

      - name: Install Dependencies on server
        run: npm install
        working-directory: api-server
