name: Next.js CI/CD

on:
  push:
    branches:
      - main  # Runs when pushing to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies on client
        run: npm install
        working-directory: client-next

      - name: Build Project client
        run: npm run build
        working-directory: client-next

      - name: Install Dependencies on server
        run: npm install
        working-directory: api-server

      - name: Start API Server
        env:
          PORT: 5001
          DB_HOST: db
          DB_PORT: 3306
          DB_USER: admin
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: traveldb
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          DATABASE_URL: ""
        run: npm run start
        working-directory: api-server